name: Docster
on: [pull_request, push]

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: kernl-sdk/docster@master
        with:
          docs_path: "apps/docs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          DAYTONA_API_KEY: ${{ secrets.DAYTONA_API_KEY }}
